package com.civileg.app.utils

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Environment
import android.widget.Toast
import androidx.core.content.FileProvider
import com.itextpdf.io.font.PdfEncodings
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.properties.BaseDirection
import com.itextpdf.layout.properties.TextAlignment
import java.io.File
import java.io.FileOutputStream

object PdfExportHelper {

    fun exportCalculationReport(
        context: Context,
        title: String,
        details: Map<String, String>,
        fileName: String
    ): String? {
        return try {
            val directory = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)
            val file = File(directory, "$fileName.pdf")
            val writer = PdfWriter(FileOutputStream(file))
            val pdf = PdfDocument(writer)
            val document = Document(pdf)

            // Header
            val arabicFont = ArabicFontProvider.getArabicPdfFont(context)
            val titlePara = Paragraph("Civil EG - Calculation Report")
                .setTextAlignment(TextAlignment.CENTER)
                .setFontSize(20f)
                .setBold()
            document.add(titlePara)
            
            document.add(LineSeparator(com.itextpdf.kernel.pdf.canvas.draw.SolidLine(1f)))
            document.add(Paragraph("\n"))
            
            // Title
            val titleP = Paragraph(title).setFontSize(16f).setBold().setUnderline()
            if (arabicFont != null && ArabicFontProvider.containsArabic(title)) {
                titleP.setFont(arabicFont)
                titleP.setBaseDirection(BaseDirection.RIGHT_TO_LEFT)
            }
            document.add(titleP)
            
            document.add(Paragraph("\n"))

            // Details
            for ((key, value) in details) {
                val p = Paragraph("$key: $value").setFontSize(12f)
                if (arabicFont != null && (ArabicFontProvider.containsArabic(key) || ArabicFontProvider.containsArabic(value))) {
                    p.setFont(arabicFont)
                    p.setBaseDirection(BaseDirection.RIGHT_TO_LEFT)
                }
                document.add(p)
            }

            document.add(Paragraph("\n\nGenerated by Civil EG App")
                .setFontSize(10f)
                .setItalic())

            document.close()
            
            openPdf(context, file)
            file.absolutePath
        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(context, "Error generating PDF: ${e.message}", Toast.LENGTH_LONG).show()
            null
        }
    }

    private fun openPdf(context: Context, file: File) {
        val uri: Uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.provider",
            file
        )
        val intent = Intent(Intent.ACTION_VIEW).apply {
            setDataAndType(uri, "application/pdf")
            flags = Intent.FLAG_GRANT_READ_URI_PERMISSION
        }
        try {
            context.startActivity(intent)
        } catch (e: Exception) {
            Toast.makeText(context, "No PDF viewer found", Toast.LENGTH_SHORT).show()
        }
    }
}

private fun LineSeparator(line: com.itextpdf.kernel.pdf.canvas.draw.ILineDrawer): com.itextpdf.layout.element.LineSeparator {
    return com.itextpdf.layout.element.LineSeparator(line)
}
